default_net_path: "inputs/case60nordic_reduced_hard.json"
n_train: 100
n_val: 10
n_test: 10
seed: 1

sampling:

  topology:
    method: "random_disconnection"
    params:
      line:
        probs:
          0: 0.2
          1: 0.2
          2: 0.2
          3: 0.2
          4: 0.2
        black_list: [25, 30, 32, 34, 36]

  total_load:
    method: "uniform_factor"
    params:
      min_val: 0.5
      max_val: 1.2

  active_load:
    method: "uniform_independent_values"
    params:
      beta: 1.0

  reactive_load:
    method: "uniform_power_factor"
    params:
      pf_min: 0.8
      pf_max:  1.
      flip_prob: 0.1

  active_gen:
    method: "dc_opf_disconnect"
    params:
      max_loading_percent: 85.
      min_cp1: 1.
      max_cp1: 2.

  voltage_setpoint:
    method: "constant"

powerflow:
  init: "results"
  enforce_q_lims: true
  delta_q: 0.0

filtering:
  max_loading_percent: 99.999
  max_count_voltage_violation: 9999
  allow_disconnected_bus: False
  allow_negative_load: False
  allow_out_of_range_gen: False
